### ISSUE TITLE
Crash with non-participating capture group

### ISSUE THREAD

**Issue by joleco** [fpg1503/Regex.swift#1]
To reproduce:
```
let regex = Regex(pattern: "(a)|b")!
let match1 = regex.matches("a")     // Captures "a"
let match2 = regex.matches("b")     // fatal error: subscript: subrange extends past String end
```

If your regular expression has captures that don't participate in the match then NSRegularExpression will give us a {NSNotFound, 0} range for that capture group and this causes a crash in substringWithRange when called from Match.init.

**Comment by fpg1503** [comment]
Thanks so much for reporting it 💙 
I'll let you know as soon as the version 1.0.2 is up on CocoaPods

**Comment by fpg1503** [comment]
Done! http://cocoapods.org/pods/Regex.swift

**Comment by joleco** [comment]
Thank you, that was quickly solved!

Is it the best solution to just omit the non-participating capture groups? Or would it be better to return empty strings?

I you match "ab" against `a(.*)|b(.*)` then you will not know if the first or the second group matched.

Ideally I suppose you'd want to know if a group participated or not but I don't think we can fix that without breaking the API. :-/

**Comment by joleco** [comment]
Well empty strings aren't good either. This will work fine. If you need that kind of control I guess you'll have to use the underlying API instead.
